version: "3.7"

services:
  api-server:
    build: ./
    container_name: "api-server"
    ports:
      - "8080:8080"
    command: go run ./cmd/scheduler/main.go
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: SchedulerDB
      DB_SSLMODE: disable
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "SchedulerDB"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./_scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/SchedulerDB?sslmode=disable
    links:
      - postgres:postgres
    restart: always
    depends_on:
      - postgres

volumes:
  postgres-data:
